package com.kafein.intern.warehouse.enums;

public enum ErrorType {

    WAREHOUSE_NAME_ALREADY_IN_USE,

    CANNOT_EDIT,
    DO_NOT_HAVE_PERMISSION,
    USER_NOT_FOUND,
    PRODUCT_CODE_ALREADY_IN_USE,
    PRODUCT_COULD_NOT_SAVE,
    CRITICAL_LEVEL,

    INVALID_REQUEST,

    WAREHOUSE_DOES_NOT_EXIST,

    PRODUCT_DOES_NOT_EXIST,
    WAREHOUSE_OR_PRODUCT_DOES_NOT_EXIST,
    INSUFFICIENT_NUMBER_OF_PRODUCTS

}
